# Generated by Django 5.2.3 on 2025-06-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Montant"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiée"),
                            ("pending", "En attente"),
                            ("success", "Succès"),
                            ("failed", "Échec"),
                        ],
                        default="initiated",
                        max_length=10,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="ID de transaction MonCash",
                    ),
                ),
                (
                    "external_order_id",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="ID de commande généré",
                    ),
                ),
                (
                    "payment_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Token de paiement"
                    ),
                ),
                (
                    "payer_phone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone du payeur"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(blank=True, verbose_name="Message de réponse"),
                ),
                (
                    "response_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Code de réponse"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to="marketplace.order",
                        verbose_name="Commande",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction de paiement",
                "verbose_name_plural": "Transactions de paiement",
            },
        ),
    ]
