# Generated by Django 5.2.3 on 2025-06-23 21:02

import django.db.models.deletion
import django.utils.timezone
import payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Reçu le"),
                ),
                ("raw_data", models.JSONField(verbose_name="Données brutes")),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="Traité"),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="Erreur de traitement"),
                ),
            ],
            options={
                "verbose_name": "Notification de paiement",
                "verbose_name_plural": "Notifications de paiement",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(max_length=15, verbose_name="Ancien statut"),
                ),
                (
                    "new_status",
                    models.CharField(max_length=15, verbose_name="Nouveau statut"),
                ),
                (
                    "changed_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Changé le"),
                ),
                (
                    "reason",
                    models.TextField(blank=True, verbose_name="Raison du changement"),
                ),
                (
                    "changed_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Changé par"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique de statut",
                "verbose_name_plural": "Historiques de statut",
                "ordering": ["-changed_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="paymenttransaction",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Transaction de paiement",
                "verbose_name_plural": "Transactions de paiement",
            },
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="api_response_data",
            field=models.JSONField(
                blank=True,
                help_text="Stockage complet de la réponse API pour debugging",
                null=True,
                verbose_name="Données de réponse API",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="currency",
            field=models.CharField(default="HTG", max_length=3, verbose_name="Devise"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="error_details",
            field=models.TextField(blank=True, verbose_name="Détails d'erreur"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Adresse IP"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="max_retries",
            field=models.PositiveIntegerField(default=3, verbose_name="Tentatives max"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payer_account",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Compte MonCash du payeur"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Paiement complété le"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expire le"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_initiated_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Paiement initié le",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("payment", "Paiement entrant"),
                    ("payout", "Paiement sortant"),
                    ("refund", "Remboursement"),
                ],
                default="payment",
                max_length=20,
                verbose_name="Type de paiement",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="redirect_url",
            field=models.URLField(
                blank=True, verbose_name="URL de redirection MonCash"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="reference",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="Référence MonCash",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="retry_count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Nombre de tentatives"
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="return_url",
            field=models.URLField(blank=True, verbose_name="URL de retour"),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="user_agent",
            field=models.TextField(blank=True, verbose_name="User Agent"),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Montant"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="external_order_id",
            field=models.CharField(
                default=payments.models.generate_order_id,
                max_length=100,
                unique=True,
                verbose_name="ID de commande généré",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_token",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="Token de paiement"
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiée"),
                    ("pending", "En attente"),
                    ("processing", "En cours de traitement"),
                    ("success", "Succès"),
                    ("failed", "Échec"),
                    ("cancelled", "Annulée"),
                    ("expired", "Expirée"),
                    ("refunded", "Remboursée"),
                ],
                default="initiated",
                max_length=15,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="transaction_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                verbose_name="ID de transaction MonCash",
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_c4e513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_c1fd68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["external_order_id"], name="payments_pa_externa_fda8a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["payment_expires_at"], name="payments_pa_payment_a5c274_idx"
            ),
        ),
        migrations.AddField(
            model_name="paymentnotification",
            name="transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="payments.paymenttransaction",
            ),
        ),
        migrations.AddField(
            model_name="paymentstatushistory",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="payments.paymenttransaction",
            ),
        ),
    ]
